### ISSUE TITLE
when test case fails, the server light-bot is not stopped

### ISSUE THREAD

**Issue by stevehu** [networknt/light-bot#62]
I have added a new test to ensure that dynamic port works with two instances of petstore services. With release 1.5.30, it should fail as we have a bug in the release. The light-bot reports the error but doesn't stop the process. Here is the stacktrace. 

```
21:37:44.772 [main]   INFO  c.n.bot.develop.DevelopBuildTask test - start testing...
21:37:45.772 [main]   INFO  c.n.bot.develop.DevelopBuildTask test - host = https://localhost:2400, path=/v1/pets/111, method=get, request header=null, request body=null
21:37:45.772 [main]   INFO  c.n.bot.develop.DevelopBuildTask test - expected status = 200 response header = {content-type=application/json} response body = {$.name=Jessica Right, $.id=1}
21:37:45.775 [main]   ERROR com.networknt.bot.core.TestUtil request - request Exception:  host = https://localhost:2400 path = /v1/pets/111 method = GET header = null
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.xnio.nio.WorkerThread$ConnectHandle.handleReady(WorkerThread.java:321)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
21:37:45.775 [main]   INFO  c.n.bot.develop.DevelopBuildTask test - shutdown servers
21:37:45.775 [main]   ERROR c.n.bot.develop.DevelopBuildTask execute - Task could not be executed and failed with: null
21:37:45.775 [main]   INFO  c.n.bot.develop.DevelopBuildTask stop - shutdown servers
21:37:45.775 [main]   INFO  com.networknt.bot.cli.Cli run - build successfully!

```

**Comment by ddobrin** [comment]
@stevehu  - My client has noticed also that the execution of the light-bot is stopping, however the messaging indicates that the process has completed successfully. 

Dependent microservices are properly stopped. 

It is an older issue which we must address for clarity, I agree
